"""empty message

Revision ID: d9265918c85c
Revises: 
Create Date: 2023-10-21 19:24:11.956090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9265918c85c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    try:
        conn.execute("SELECT 1 FROM summary LIMIT 1;")
    except OperationalError:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('summary',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(length=512), nullable=False),
        sa.Column('summary_text', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary')
    # ### end Alembic commands ###
